# POST  http://localhost:3003/api/blogs
# Content-Type: application/json

# {
# "title": "The popoapooappoaapiaipos blog in the list picking a random username and name",
# "author": "TryMe",
# "url": "www.8blog.com",
# "likes": 2982829387393

# }


POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Super Mario",
  "name": "Bross",
  "password": "salainen"
}



# POST  http://localhost:3003/api/login
# Content-Type: application/json

# {
#     "username": "root",
#     "password": "salainen"
# }